# Uncomment the next line to define a global platform for your project

platform :ios, '16.0'

target 'DCUSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'DCU', :path => '../'
end

target 'DCUSample2.0' do

#   use_frameworks!
   pod 'DCU/DCU2.0', :path => '../'

end
